# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=db_users
  symfony-test-technique:
    image: docker.io/bitnami/symfony:6.3
    ports:
      - '8000:8000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=admin
      - SYMFONY_DATABASE_NAME=db_users
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './symphony-project:/app'
    depends_on:
      - mariadb
